name: weatherapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
#  Plugin Weather Settings
  weather: ^3.1.1
#  Plugin Date Format
  intl: ^0.19.0
#  Plugin State Manaegement
  flutter_bloc: ^8.1.5
#  Plugin Maps
  geolocator: ^11.0.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
